//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _24052021AgendaConsulta
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConsultaDBEntities : DbContext
    {
        public ConsultaDBEntities()
            : base("name=ConsultaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TB_PACIENTE> TB_PACIENTE { get; set; }
        public virtual DbSet<TB_CONSULTA> TB_CONSULTA { get; set; }

        internal Consulta SelectById(object id)
        {
            throw new NotImplementedException();
        }
    }
}
